# Generated by Django 2.1.7 on 2019-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190419_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default=0, max_length=100, verbose_name='가격'),
            preserve_default=False,
        ),
    ]
